
import requests
import time
import os
import datetime
import json

BASE_URL = "http://localhost:8000"
TIMESTAMP = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
TEST_FILENAME = f"EXHAUSTIVE_TEST_{TIMESTAMP}.txt"
TEST_FILE_PATH = os.path.abspath(TEST_FILENAME)

GREEN = "\033[92m"
RED = "\033[91m"
BLUE = "\033[94m"
RESET = "\033[0m"

def log(msg, color=RESET):
    print(f"{color}{msg}{RESET}")

def test_status():
    log("\n[1] TESTING SYSTEM STATUS...", BLUE)
    try:
        r = requests.get(f"{BASE_URL}/v1/system/status")
        if r.status_code == 200:
            data = r.json()
            log(f"[PASS] Status: 200 OK", GREEN)
            log(f"   Active Stack: {data.get('active_stack')}")
            log(f"   TTS: {data.get('technologies', {}).get('tts', {}).get('active_engine')}")
        else:
            log(f"[FAIL] Status: {r.status_code}", RED)
    except Exception as e:
        log(f"[FAIL] Connection Failed: {e}", RED)

def test_tts():
    log("\n[2] TESTING TTS (SPEAK)...", BLUE)
    text = "Executing exhaustive diagnostic protocol. All systems verified."
    try:
        r = requests.post(f"{BASE_URL}/v1/tts/speak", json={"text": text})
        if r.status_code == 200:
            log(f"[PASS] TTS Request: 200 OK", GREEN)
            log(f"   Message: {r.json().get('message')}")
        else:
            log(f"[FAIL] TTS Failed: {r.status_code}", RED)
    except Exception as e:
        log(f"[FAIL] TTS Error: {e}", RED)

def test_llm():
    log("\n[3] TESTING LLM (THINK)...", BLUE)
    prompt = "Explain briefly what is an API in one sentence."
    try:
        r = requests.post(f"{BASE_URL}/v1/llm/think", json={"prompt": prompt})
        if r.status_code == 200:
            data = r.json()
            response = data.get("response", {})
            # Handle different brain response formats (raw str or json)
            thought = response.get("thought") if isinstance(response, dict) else "N/A"
            log(f"[PASS] LLM Response: 200 OK", GREEN)
            log(f"   Thought: {thought}")
        else:
            log(f"[FAIL] LLM Failed: {r.status_code}", RED)
    except Exception as e:
        log(f"[FAIL] LLM Error: {e}", RED)

def test_action_file_creation():
    log("\n[4] TESTING ACTION (CREATE DETAILED FILE)...", BLUE)
    
    content = f"""
    HABLAME SYSTEM DIAGNOSTIC REPORT
    ================================
    Date: {datetime.datetime.now()}
    Test ID: {TIMESTAMP}
    
    1. connectivity: Verified
    2. audio_output: Verified
    3. intelligence: Verified
    
    This file was automatically generated by the Hablame Action Engine 
    to demonstrate OS-level write capabilities via the API.
    
    End of Report.
    """
    
    command = f"Create a file named {TEST_FILENAME} with this content: {content}"
    
    log(f"   Target File: {TEST_FILE_PATH}")
    log(f"   Command: Create file...", BLUE)
    
    try:
        r = requests.post(f"{BASE_URL}/v1/action/execute", json={"command": command})
        
        if r.status_code == 200:
            log(f"[PASS] API Request: 200 OK", GREEN)
            
            # VERIFY ON DISK
            if os.path.exists(TEST_FILE_PATH):
                log(f"[PASS] FILE VALIDATION: SUCCESS", GREEN)
                log(f"   File found at: {TEST_FILE_PATH}")
                file_size = os.path.getsize(TEST_FILE_PATH)
                log(f"   Size: {file_size} bytes")
                
                with open(TEST_FILE_PATH, 'r') as f:
                    saved_content = f.read()
                    
                log(f"   --- Content Preview ---")
                print(saved_content.strip())
                log(f"   -----------------------")
            else:
                log(f"[FAIL] FILE VALIDATION: FAILED (File not found on disk)", RED)
        else:
            log(f"[FAIL] Action Failed: {r.status_code} - {r.text}", RED)
            
    except Exception as e:
        log(f"[FAIL] Action Error: {e}", RED)

def main():
    log("==========================================")
    log("   EXHAUSTIVE API TEST SUITE STARTED      ")
    log("==========================================")
    
    start_time = time.time()
    
    test_status()
    test_tts()
    test_llm()
    test_action_file_creation()
    
    end_time = time.time()
    duration = round(end_time - start_time, 2)
    
    log("\n==========================================")
    log(f"   TESTS COMPLETED in {duration}s")
    log("==========================================")

if __name__ == "__main__":
    main()
